Update methods in README.md with asset elements
Kentico/kontent-management-sdk-net pull request #148
Opened 2022-03-08 10:57 UTC by Simcsa

### Motivation

Fixes #144.

Contains updates to readme with the new asset taxonomies functionality examples. I also fixed all the asset code samples to be up to date.

### Checklist

- [ ] Code follows coding conventions held in this repo
- [ ] Automated tests have been added
- [ ] Tests are passing
- [ ] Docs have been updated (if applicable)
- [ ] Temporary settings (e.g. variables used during development and testing) have been reverted to defaults

### How to test

No need to test

2022-03-09 09:19 UTC, Suzii commented
Shouldn't this PR be pointed at vNext branch?

2022-03-09 16:30 UTC, gormal commented
> Shouldn't this PR be pointed at vNext branch?
Yes, this change belongs to vNext branch, however the readme.md is quite different there. I would suggest adding a new section "Working with assets" that would contain info about dynamic assets vs strongly typed assets and a simple code sample on how to create assets in both categories.

@Simply007 what do you think?

2022-03-09 17:09 UTC, Simply007 commented
There is also a https://github.com/Kentico/kontent-management-sdk-net/blob/vNext/Kentico.Kontent.Management.Tests/Unit/CodeSamples/Readme.cs file with all existing code samples for  README to just verify the code is compilable.

2022-03-10 15:20 UTC, Simcsa commented
Okay, I added "Working with assets" section with two examples. The PR is now pointed to the vNext branch. The unit tests were updated.

2022-03-10 15:40 UTC, gormal requested changes
Looks great to me, there is just one comment.

2022-03-10 16:10 UTC, Simcsa commented on Kentico.Kontent.Management.Tests/Unit/CodeSamples/Readme.cs
> +            var response = await client.UpsertAssetByExternalIdAsync(externalId, asset);
UpdateAssetAsync used

2022-03-10 16:20 UTC, merged