Feature/69 clean up
Kentico/kontent-management-sdk-net pull request #164
Opened 2022-03-23 20:39 UTC by gormal

### Motivation

Which issue does this fix? Fixes #`issue number`

If no issue exists, what is the fix or new feature? Were there any reasons to fix/implement things that are not obvious?

### Checklist

- [ ] Code follows coding conventions held in this repo
- [ ] Automated tests have been added
- [ ] Tests are passing
- [ ] Docs have been updated (if applicable)
- [ ] Temporary settings (e.g. variables used during development and testing) have been reverted to defaults

### How to test

If manual testing is required, what are the steps?

2022-03-25 20:24 UTC, winklertomas requested changes

2022-03-25 20:24 UTC, winklertomas commented on Kentico.Kontent.Management.Tests/Base/FileSystemFixture.cs
> +    private readonly ManagementOptions _managementOptions;
can be converted to local variable

2022-03-25 20:24 UTC, winklertomas commented on Kentico.Kontent.Management.Tests/ManagementHttpClientTests.cs
unused using System.Collections.Generic;

2022-03-30 13:59 UTC, gormal commented on Kentico.Kontent.Management.Tests/CodeSamples/Readme.cs
> -            _ = new ManagementClient(new ManagementOptions
This is file should contain code samples used in Readme.md and it just looks better with `var client`

2022-03-30 14:10 UTC, gormal commented on Kentico.Kontent.Management.Tests/ManagementClientTests/AssetTests.cs
> +        }.Select(x => GetExpectedDynamicAssetModel(assetId: x));
The build-in analyzer does not offer this refactoring, so I won't enforce it.

2022-03-30 14:11 UTC, gormal commented on Kentico.Kontent.Management.Tests/ManagementClientTests/AssetTests.cs
> +        }.Select(x => GetExpectedStronglyTypedAssetModel(assetId: x));
The build-in analyzer does not offer this refactoring, so I won't enforce it.

2022-03-30 14:11 UTC, gormal commented on Kentico.Kontent.Management/ManagementClient.cs
> +                (token, url) => GetNextListingPageAsync<LanguageVariantsListingResponseServerModel, LanguageVariantModel>(token, url),
The build-in analyzer does not offer this refactoring, so I won't enforce it.

2022-03-30 14:11 UTC, gormal commented on Kentico.Kontent.Management/Modules/ActionInvoker/DynamicObjectJsonConverter.cs
> +                resultAsDictionary.Add(property.Name, array.Select(arrayObject => ConvertJComplexObject(arrayObject)));
The build-in analyzer does not offer this refactoring, so I won't enforce it.

2022-03-30 14:11 UTC, gormal commented on Kentico.Kontent.Management/Modules/ActionInvoker/DynamicObjectJsonConverter.cs
> +        JArray array => array.Select(obj => ConvertJComplexObject(obj)),
The build-in analyzer does not offer this refactoring, so I won't enforce it.

2022-03-30 14:12 UTC, gormal commented on Kentico.Kontent.Management.Tests/ManagementClientTests/ContentTypeTests.cs
> +        List<ContentTypeOperationBaseModel> changes = new() { };
fixed

2022-03-30 14:13 UTC, gormal commented on Kentico.Kontent.Management/Models/Subscription/SubscriptionProjectListingResponseServerModel.cs
> +    public IEnumerator<SubscriptionProjectModel> GetEnumerator() => GetEnumerator();
Uff, good catch :)

2022-03-30 14:13 UTC, gormal commented on Kentico.Kontent.Management.Tests/Base/FileSystemFixture.cs
> +    private readonly ManagementOptions _managementOptions;
fixed

2022-03-30 14:15 UTC, gormal commented on Kentico.Kontent.Management.Tests/CodeSamples/CmApiV2.cs
> +                    new TaxonomyTermCreateModel
The build-in analyzer didn't pick this up, so I will leave it as I want to be independent of R#

2022-03-30 14:15 UTC, gormal commented on Kentico.Kontent.Management.Helpers.Tests/EditLinkBuilderTests.cs
> +            new ElementIdentifier("76c06b74-bae9-4732-b629-1a59395e893d", "some-Element-Codename-1"),
The build-in analyzer didn't pick this up, so I will leave it as I want to be independent of R#

2022-03-30 14:19 UTC, gormal commented on Kentico.Kontent.Management/Modules/ActionInvoker/DynamicObjectJsonConverter.cs
> +        _ => throw new ArgumentOutOfRangeException("JSON deserialization did not return either object nor array."),
fixed

2022-03-30 14:19 UTC, gormal commented on Kentico.Kontent.Management/Modules/ModelBuilders/ElementBuilder.cs
> +                elementExceptions.Add(new ArgumentNullException("Element identifier (`BaseElement.Element` property) not set for element on index ", Array.IndexOf(elements, elementObject).ToString())
fixed

2022-03-31 08:37 UTC, winklertomas commented on Kentico.Kontent.Management.Tests/Data/ElementsData.cs
> +            new ComponentModel
Yes the R# suggests that.

2022-03-31 08:37 UTC, gormal commented on Kentico.Kontent.Management.Tests/ManagementClientTests/ContentTypeSnippetTests.cs
> +namespace Kentico.Kontent.Management.Tests.Unit.ManagementClientTests;
fixed

2022-03-31 08:43 UTC, winklertomas approved these changes
Review ok, feel free to merge it :-)

2022-03-31 09:02 UTC, gormal commented
This can be merged only after #163.

2022-03-31 14:57 UTC, merged